### ISSUE TITLE
Fix the mcpe example

### ISSUE THREAD

**Issue by Adrian8115** [dermesser/leveldb-rs#45]
The mcpe example is broken and doesn't work anymore.
Some things have changed in the mcpe dbs and are not the same as they were. It would be lovely if this awesome example would be updated.

When running I get the error:
```rust
called `Result::unwrap()` on an `Err` value: Status { code: NotSupported, err: "invalid compression id `4`" }
```

**Comment by dermesser** [comment]
Unfortunately it's not me who has contributed this, and I don't know how to fix it. @KAIYOHUGO is the original author for all I can see - maybe they can take a look?

**Comment by KAIYOHUGO** [comment]
I think mojang's leveldb format change a lot since I wrote this example, and original [mojang version of leveldb](https://github.com/Mojang/leveldb-mcpe) is disappear. 
From the copy  in [other repo](https://github.com/reedacartwright/rbedrock/tree/fb32a899da4e15c1aaa0d6de2b459e914e183516/src/leveldb-mcpe), I think compression id 4 is [leveldb_zlib_raw_compression](https://github.com/reedacartwright/rbedrock/blob/fb32a899da4e15c1aaa0d6de2b459e914e183516/src/leveldb-mcpe/include/leveldb/c.h#L199). From my understand, `leveldb_zlib_raw_compression` is the same as `leveldb_zlib_compression` [^1]

I also need to mention that mojang's format is quite quirky, sometime it just don't work and I don't know why.

[^1]: 
    [They all base on `ZlibCompressorBase`](https://github.com/reedacartwright/rbedrock/blob/fb32a899da4e15c1aaa0d6de2b459e914e183516/src/leveldb-mcpe/include/leveldb/zlib_compressor.h)
    
    [`ZlibCompressorBase`'s implementation](https://github.com/reedacartwright/rbedrock/blob/fb32a899da4e15c1aaa0d6de2b459e914e183516/src/leveldb-mcpe/db/zlib_compressor.cc)

**Comment by Adrian8115** [comment]
I sadly tried both `leveldb_zlib_raw_compression` and `leveldb_zlib_compression` for compression id 4, neither worked. Even though the original library disappeared it would still be nice to have this as an up to date example because it is a really practical and useful example.
I am also very thankful that this library is well maintained!

**Comment by KAIYOHUGO** [comment]
@Adrian8115 I made some patch and more detail comment in the [fork](https://github.com/KAIYOHUGO/leveldb-rs), can you test the problem still persist?

**Comment by Adrian8115** [comment]
Thank you so much!
It works great...

**Comment by dermesser** [comment]
Thank you so much @KAIYOHUGO for fixing it, and @Adrian8115 for bringing it to our attention :)

**Comment by Adrian8115** [comment]
@KAIYOHUGO also thanks for the additional documentation!
